// src/lib/dhfPdf.ts
// Generate a styled PDF for a single DHF document, or a full DHF portfolio bundle.
// Uses jsPDF (added in package.json). Pure browser, no server needed.

import jsPDF from "jspdf";

export interface DhfDoc {
  doc_code: string;
  doc_title: string;
  doc_section?: string | null;
  body_markdown: string;
  created_at?: string;
  score?: number;
}

const NAVORO_GREEN = "#064635";
const NAVORO_GOLD = "#D4AF37";

const drawHeader = (pdf: jsPDF, owner: string) => {
  pdf.setFillColor(NAVORO_GREEN);
  pdf.rect(0, 0, 210, 22, "F");
  pdf.setTextColor("#ffffff");
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(14);
  pdf.text("NAVORO  /  DHF Portfolio", 14, 14);
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(9);
  pdf.text(`Owner: ${owner}`, 200 - 14, 14, { align: "right" });
};

const drawFooter = (pdf: jsPDF, page: number, total: number) => {
  pdf.setDrawColor(NAVORO_GOLD);
  pdf.setLineWidth(0.4);
  pdf.line(14, 285, 196, 285);
  pdf.setTextColor("#666666");
  pdf.setFontSize(8);
  pdf.text(
    "CardioSense Pro — Design History File  •  Generated by Navoro",
    14,
    291,
  );
  pdf.text(`Page ${page} / ${total}`, 196, 291, { align: "right" });
};

const writeDocBody = (pdf: jsPDF, doc: DhfDoc, startY: number) => {
  let y = startY;

  pdf.setTextColor(NAVORO_GREEN);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(18);
  pdf.text(`${doc.doc_code} — ${doc.doc_title}`, 14, y);
  y += 8;

  if (doc.doc_section) {
    pdf.setFont("helvetica", "italic");
    pdf.setTextColor("#555555");
    pdf.setFontSize(10);
    pdf.text(doc.doc_section, 14, y);
    y += 7;
  }

  if (doc.created_at) {
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor("#888888");
    pdf.setFontSize(8);
    pdf.text(`Authored: ${new Date(doc.created_at).toLocaleString()}`, 14, y);
    y += 6;
  }

  pdf.setDrawColor(NAVORO_GOLD);
  pdf.setLineWidth(0.6);
  pdf.line(14, y, 60, y);
  y += 6;

  pdf.setTextColor("#222222");
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);

  const body = doc.body_markdown.replace(/\r\n/g, "\n");
  const blocks = body.split("\n\n");

  for (const block of blocks) {
    if (!block.trim()) continue;
    const isHeading = /^#{1,6}\s/.test(block.trim());
    if (isHeading) {
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(12);
      pdf.setTextColor(NAVORO_GREEN);
    } else {
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(10.5);
      pdf.setTextColor("#222222");
    }
    const clean = block.replace(/^#{1,6}\s+/, "").replace(/\*\*(.+?)\*\*/g, "$1");
    const lines = pdf.splitTextToSize(clean, 182);
    if (y + lines.length * 5.4 > 275) {
      pdf.addPage();
      y = 32;
    }
    pdf.text(lines, 14, y);
    y += lines.length * 5.4 + 3;
  }

  return y;
};

export const downloadSingleDhfPdf = (doc: DhfDoc, owner: string) => {
  const pdf = new jsPDF({ unit: "mm", format: "a4" });
  drawHeader(pdf, owner);
  writeDocBody(pdf, doc, 32);
  drawFooter(pdf, 1, pdf.getNumberOfPages());
  // Re-stamp every page's footer with correct total
  const total = pdf.getNumberOfPages();
  for (let p = 1; p <= total; p++) {
    pdf.setPage(p);
    drawFooter(pdf, p, total);
    if (p === 1) continue;
    drawHeader(pdf, owner);
  }
  pdf.save(`${doc.doc_code}_${doc.doc_title.replace(/[^a-z0-9]+/gi, "_")}.pdf`);
};

export const downloadFullDhfPortfolio = (docs: DhfDoc[], owner: string) => {
  const pdf = new jsPDF({ unit: "mm", format: "a4" });

  // Cover page
  drawHeader(pdf, owner);
  pdf.setTextColor(NAVORO_GREEN);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(28);
  pdf.text("Design History File", 14, 70);
  pdf.text("CardioSense Pro (Class II)", 14, 82);

  pdf.setDrawColor(NAVORO_GOLD);
  pdf.setLineWidth(0.8);
  pdf.line(14, 90, 90, 90);

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);
  pdf.setTextColor("#333333");
  pdf.text(`Owner: ${owner}`, 14, 102);
  pdf.text(`Generated: ${new Date().toLocaleString()}`, 14, 110);
  pdf.text(`Total controlled documents: ${docs.length}`, 14, 118);

  pdf.setTextColor(NAVORO_GREEN);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(14);
  pdf.text("Index", 14, 140);

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10);
  pdf.setTextColor("#222222");
  docs.forEach((d, i) => {
    pdf.text(`${(i + 1).toString().padStart(2, "0")}.  ${d.doc_code} — ${d.doc_title}`, 14, 150 + i * 6);
  });

  // One page per doc
  docs.forEach((d) => {
    pdf.addPage();
    drawHeader(pdf, owner);
    writeDocBody(pdf, d, 32);
  });

  const total = pdf.getNumberOfPages();
  for (let p = 1; p <= total; p++) {
    pdf.setPage(p);
    drawFooter(pdf, p, total);
  }
  pdf.save(`CardioSense_Pro_DHF_${owner.replace(/\s+/g, "_")}.pdf`);
};
